# fix fuking stupid pdb file generated by packmol

import os

os.chdir('C:\\Users\\03022\\Desktop')

def fixline(l):
    s = l.split('.')
    l = s[0] + '.' + s[1][0:3] + ' ' + s[1][3:] + '.' + s[2][0:3] + ' ' + s[2][3:] + '.' + s[3][0:3] + '\n'
    return l     

with open('pgn-out-success.pdb') as f:
    lines = f.readlines()[5:-1]
    for i in range(len(lines)): 
        lines[i] = fixline(lines[i])
    
    with open('pgnpmf109.pdb', 'x') as g:
        g.writelines(f.readlines()[0:5])
        g.writelines(lines)

