# fix fuking stupid pdb file generated by packmol

import os
import sys

os.chdir('/home/jjq4271/pgnpmf/packmol')

def fixline(l):
    s = l.split('.')
    l = s[0] + '.' + s[1][0:3] + ' ' + s[1][3:] + '.' + s[2][0:3] + ' ' + s[2][3:] + '.' + s[3][0:3] + '\n'
    return l     

with open(sys.argv[1]) as f:
    lines = f.readlines()[5:-1]
    for i in range(len(lines)): 
        lines[i] = fixline(lines[i])
    
    with open(sys.argv[2], 'x') as g:
        g.writelines(f.readlines()[0:5])
        g.writelines(lines)

